-- Alias
insert into aliases (icon_image_id, display_name)
values ('actor-chaplin-comedy-svgrepo-com_syujst', 'Thằng Hề Hài Hước'),
       ('addicted-draw-love-svgrepo-com_fqz3ji', 'Kẻ Nghiện Yêu'),
       ('afro-avatar-male-2-svgrepo-com_yzvudo', 'Anh Chàng Afro 2'),
       ('afro-avatar-male-svgrepo-com_ytzmk1', 'Anh Chàng Afro 1'),
       ('afro-boy-child-svgrepo-com_likue8', 'Cậu Bé Afro'),
       ('afro-female-person-svgrepo-com_hfeobm', 'Cô Nàng Afro'),
       ('alien-avatar-space-svgrepo-com_dtnccn', 'Người Ngoài Hành Tinh'),
       ('animal-avatar-bear-svgrepo-com_zkxuq0', 'Gấu Bông Bí Ẩn'),
       ('animal-avatar-mutton-svgrepo-com_mkd69z', 'Cừu Bông Mơ Màng'),
       ('anime-away-face-svgrepo-com_iuh0xo', 'Chàng Trai Anime Lạc Lối'),
       ('apple-avatar-illness-svgrepo-com_ohmzhq', 'Quả Táo Bệnh Tật'),
       ('artist-avatar-marilyn-svgrepo-com_ems6gg', 'Họa Sĩ Marilyn'),
       ('avatar-avocado-food-svgrepo-com_tsj9oc', 'Quả Bơ Thơm Ngon'),
       ('avatar-bad-breaking-svgrepo-com_r59rbo', 'Kẻ Phá Đám'),
       ('avatar-batman-comics-svgrepo-com_lmcuwg', 'Người Dơi Bí Ẩn'),
       ('avatar-boy-kid-svgrepo-com_j8rwm4', 'Thằng Nhóc Confession'),
       ('avatar-boy-male-svgrepo-com_ejsjq5', 'Chàng Trai Tuổi Teen'),
       ('avatar-bug-insect-svgrepo-com_drbpsp', 'Chú Bọ Đáng Yêu'),
       ('avatar-cacti-cactus-svgrepo-com_p24ixb', 'Xương Rồng Mạnh Mẽ'),
       ('avatar-child-girl-svgrepo-com_frwoit', 'Cô Bé Bí Mật'),
       ('avatar-cloud-crying-svgrepo-com_ekle5b', 'Mây Buồn Thầm Kín'),
       ('avatar-coffee-cup-svgrepo-com_lmqngl', 'Tách Cà Phê Tỉnh Táo'),
       ('avatar-dead-monster-svgrepo-com_q3c8b8', 'Quái Vật Bí Ẩn'),
       ('avatar-einstein-professor-svgrepo-com_r7s7we', 'Thầy Giáo Lắm Bí Mật'),
       ('avatar-elderly-grandma-svgrepo-com_e9r45j', 'Bà Ngoại Hiền Hậu'),
       ('avatar-female-girl-svgrepo-com_hfc8ni', 'Cô Nàng Bí Ẩn'),
       ('avatar-female-portrait-2-svgrepo-com_pcsfof', 'Cô Gái Dịu Dàng'),
       ('avatar-female-portrait-svgrepo-com_b69xm5', 'Nàng Thơ Mơ Màng'),
       ('avatar-geisha-japanese-svgrepo-com_gczw9a', 'Nàng Geisha Mơ Màng'),
       ('avatar-hindi-indian-svgrepo-com_lbsvag', 'Chàng Trai Ấn Độ'),
       ('avatar-joker-squad-svgrepo-com_guj1qa', 'Gã Hề Confession'),
       ('avatar-lazybones-sloth-svgrepo-com_t6me9f', 'Gấu Lười Tí Hon'),
       ('avatar-male-man-svgrepo-com_jm1cpr', 'Anh Chàng Mặt Trời'),
       ('avatar-male-ozzy-svgrepo-com_flptem', 'Ông Chú Cool Ngầu'),
       ('avatar-male-president-svgrepo-com_g9eawm', 'Ông Chủ Bí Ẩn'),
       ('avatar-man-muslim-svgrepo-com_rccrpe', 'Anh Chàng Hồi Giáo'),
       ('avatar-man-person-svgrepo-com_q0v237', 'Chàng Trai Bí Ẩn'),
       ('avatar-muslim-paranja-svgrepo-com_njj5xa', 'Bóng Ma Bí Ẩn'),
       ('avatar-nun-sister-svgrepo-com_eg3obl', 'Sơ Duyên Dáng'),
       ('avatar-person-pilot-svgrepo-com_adxznw', 'Phi Công Bí Ẩn'),
       ('baby-child-kid-svgrepo-com_s2lxjt', 'Em Bé Hồn Nhiên'),
       ('beard-hipster-male-svgrepo-com_yhlchy', 'Chàng Râu Hipster'),
       ('boy-indian-kid-svgrepo-com_qmcdvw', 'Cậu Bé Ấn Độ'),
       ('builder-helmet-worker-svgrepo-com_ldihet', 'Anh Thợ Xây'),
       ('child-girl-kid-svgrepo-com_sb6rb0', 'Cô Bé Tinh Nghịch'),
       ('christmas-clous-santa-svgrepo-com_pvzzbg', 'Ông Già Noel'),
       ('fighter-luchador-man-svgrepo-com_scbtk8', 'Chiến Binh Lucha'),
       ('friday-halloween-jason-svgrepo-com_nlxd1a', 'Sát Nhân Halloween'),
       ('indian-male-man-svgrepo-com_ds3men', 'Chàng Trai Ấn Độ 2'),
       ('indian-man-sikh-svgrepo-com_tqglec', 'Chàng Sikh Đặc Biệt'),
       ('male-man-old-svgrepo-com_vwu862', 'Ông Già Thân Thiện');


