INSERT INTO schools (logo_image_id, name, short_name, type, is_active)
VALUES ('AGU_x4ab1a', 'Đại học An Giang', 'AGU', 'university', false),
       ('AJC_yywvmv', 'Học viện Báo chí và Tuyên truyền', 'AJC', 'academy', false),
       ('AOF_ke88b8', 'Học viện Tài chính', 'AOF', 'academy', false),
       ('APD_fflxw4', 'Học viện Chính sách và Phát triển', 'APD', 'academy', false),
       ('BA_u1fr9m', 'Học viện Ngân hàng', 'BA', 'academy', false),
       ('CTU_jtbg3z', 'Đại học Cần Thơ', 'CTU', 'university', false),
       ('CTUT_psmug2', 'Đại học Kỹ thuật - Công nghệ Cần Thơ', 'CTUT', 'university', false),
       ('DAV_lccmes', 'Học viện Ngoại giao', 'DAV', 'academy', false),
       ('DTH_hwlzud', 'Đại học Đồng Tháp', 'DTH', 'university', false),
       ('DUE_nin6ky', 'Đại học Kinh tế - ĐH Đà Nẵng', 'DUE', 'university', false),
       ('DUED_ez04be', 'Đại học Sư phạm - ĐH Đà Nẵng', 'DUED', 'university', false),
       ('DUT_wqzbgm', 'Đại học Bách khoa - ĐH Đà Nẵng', 'DUT', 'university', false),
       ('FTU_xwvqtk', 'Đại học Ngoại thương', 'FTU', 'university', false),
       ('GDU_d2023l', 'Đại học Gia Định', 'GDU', 'university', false),
       ('HAU_go5b6r', 'Đại học Kiến trúc Hà Nội', 'HAU', 'university', false),
       ('HCE_fp7cdr', 'Đại học Kinh tế - ĐH Huế', 'HCE', 'university', false),
       ('HCMIU_f34ptp', 'Đại học Quốc tế - ĐHQG TP.HCM', 'HCMIU', 'university', false),
       ('HCMUE_hnpvbo', 'Đại học Sư phạm TP.HCM', 'HCMUE', 'university', false),
       ('HCMUF_uiomu1', 'Đại học Mỹ thuật TP.HCM', 'HCMUF', 'university', false),
       ('HCMULAW_n5cygv', 'Đại học Luật TP.HCM', 'HCMULAW', 'university', false),
       ('HCMUS_prwnmd', 'Đại học Khoa học Tự nhiên - ĐHQG TP.HCM', 'HCMUS', 'university', false),
       ('HCMUSSH_ibkfcz', 'Đại học Khoa học Xã hội và Nhân văn - ĐHQG TP.HCM', 'HCMUSSH', 'university', false),
       ('HCMUT_fvpinn', 'Đại học Bách khoa - ĐHQG TP.HCM', 'HCMUT', 'university', false),
       ('HCMUTE_npkqtq', 'Đại học Sư phạm Kỹ thuật TP.HCM', 'HCMUTE', 'university', false),
       ('HIU_icgjlc', 'Đại học Quốc tế Hồng Bàng', 'HIU', 'university', false),
       ('HLU_ybzovj', 'Đại học Luật Hà Nội', 'HLU', 'university', false),
       ('HNUE_z6jpxm', 'Đại học Sư phạm Hà Nội', 'HNUE', 'university', false),
       ('HOU_sejkzw', 'Đại học Mở TP.HCM', 'HOU', 'university', false),
       ('HUA_mbzoyw', 'Đại học Nghệ thuật - ĐH Huế', 'HUA', 'university', false),
       ('HUAF_oa9exx', 'Đại học Nông Lâm - ĐH Huế', 'HUAF', 'university', false),
       ('HUB_ixtbq9', 'Đại học Ngân hàng TP.HCM', 'HUB', 'university', false),
       ('HUCE_jrcy8v', 'Đại học Sư phạm - ĐH Huế', 'HUCE', 'university', false),
       ('HUCFL_chojpr', 'Đại học Ngoại ngữ - ĐH Huế', 'HUCFL', 'university', false),
       ('HUE_xo2mzx', 'Đại học Huế', 'HUE', 'university', false),
       ('HUFI_a0bigv', 'Đại học Công nghiệp Thực phẩm TP.HCM', 'HUFI', 'university', false),
       ('HUFLIT_ka21nb', 'Đại học Ngoại ngữ - Tin học TP.HCM', 'HUFLIT', 'university', false),
       ('HUI_taceq3', 'Đại học Công nghiệp Hà Nội', 'HUI', 'university', false),
       ('HUL_nas8xw', 'Đại học Luật - ĐH Huế', 'HUL', 'university', false),
       ('HUMG_t0ah4h', 'Đại học Mỏ - Địa chất', 'HUMG', 'university', false),
       ('HUP_luc3pd', 'Đại học Dược Hà Nội', 'HUP', 'university', false),
       ('HUS_n03yoz', 'Đại học Khoa học Tự nhiên - ĐHQGHN', 'HUS', 'university', false),
       ('HUSC_jwd8ql', 'Đại học Khoa học - ĐH Huế', 'HUSC', 'university', false),
       ('HUST_qk2spi', 'Đại học Bách khoa Hà Nội', 'HUST', 'university', false),
       ('HUTECH_bnzh8j', 'Đại học Công nghệ TP.HCM', 'HUTECH', 'university', false),
       ('HVU_mgylk1', 'Đại học Hùng Vương TP.HCM', 'HVU', 'university', false),
       ('IUH_ehrjwb', 'Đại học Công nghiệp TP.HCM', 'IUH', 'university', false),
       ('KGU_isbjhn', 'Đại học Kiên Giang', 'KGU', 'university', false),
       ('KMA_tilbfs', 'Học viện Kỹ thuật Mật mã', 'KMA', 'academy', false),
       ('LHU_zpqxqs', 'Đại học Lạc hồng ', 'LHU', 'university', false),
       ('NAEM_m6cwg6', 'Học viện Quản lý giáo dục', 'NAEM', 'academy', false),
       ('NAPA_vhefvd', 'Học viện Hành chính Quốc gia', 'NAPA', 'academy', false),
       ('NCTU_utrp0e', 'Đại học Nam Cần Thơ', 'NCTU', 'university', false),
       ('NEU_rv6wo1', 'Đại học Kinh tế Quốc dân', 'NEU', 'university', false),
       ('NTTU_xdddcm', 'Đại học Nguyễn Tất Thành', 'NTTU', 'university', false),
       ('PNTU_rpvm36', 'Đại học Y khoa Phạm Ngọc Thạch', 'PNTU', 'university', false),
       ('SGU_fv7xxs', 'Đại học Sài Gòn', 'SGU', 'university', false),
       ('SIU_v9dblb', 'Đại học Quốc tế Sài Gòn', 'SIU', 'university', false),
       ('SKDA_prsu98', 'Đại học Sân khấu - Điện ảnh TP.HCM', 'SKDA', 'university', false),
       ('TDTU_cpahcf', 'Đại học Tôn Đức Thắng', 'TDTU', 'university', false),
       ('TPU_pg6kwx', 'Đại học Tây Đô', 'TDU', 'university', false),
       ('TVU_woohty', 'Đại học Trà Vinh', 'TVU', 'university', false),
       ('UD_hjunhs', 'Đại học Đà Nẵng', 'UD', 'university', false),
       ('UEB_etffhr', 'Đại học Kinh tế - ĐHQGHN', 'UEB', 'university', false),
       ('UED_vj3ike', 'Đại học Giáo dục - ĐHQGHN', 'UED', 'university', false),
       ('UEH_rphl2i', 'Đại học Kinh tế TP.HCM', 'UEH', 'university', false),
       ('UEL_tlb6cm', 'Đại học Kinh tế - Luật - ĐHQG TP.HCM', 'UEL', 'university', false),
       ('UET_kyzmtw', 'Đại học Công nghệ - ĐHQGHN', 'UET', 'university', false),
       ('UFLS_i0h5a4', 'Đại học Ngoại ngữ - ĐH Đà Nẵng', 'UFLS', 'university', false),
       ('UFM_ozao1x', 'Đại học Tài chính - Marketing', 'UFM', 'university', false),
       ('UIT_yygh6t', 'Đại học Công nghệ Thông tin - ĐHQG TP.HCM', 'UIT', 'university', false),
       ('UMP_yjoyc5', 'Đại học Y Dược TP.HCM', 'UMP', 'university', false),
       ('UPES_rod7jj', 'Đại học Sư phạm Thể dục Thể thao TP.HCM', 'UPES', 'university', false),
       ('USH_njg5cl', 'Đại học Thể dục Thể thao TP.HCM', 'USH', 'university', false),
       ('UTC_atvcfz', 'Đại học Giao thông Vận tải', 'UTC', 'university', false),
       ('UTE_t0iooo', 'Đại học Sư phạm Kỹ thuật - ĐH Đà Nẵng', 'UTE', 'university', false),
       ('UTH_omikkw', 'Đại học Giao thông Vận tải TP.HCM', 'UTH', 'university', true),
       ('VHU_y6z9uz', 'Đại học Văn Hiến', 'VHU', 'university', false),
       ('VJU_wjgy5h', 'Đại học Việt Nhật - ĐHQGHN', 'VJU', 'university', false),
       ('VKU_gsnayw', 'Đại học Công nghệ Thông tin và Truyền thông Việt – Hàn', 'VKU', 'university', false),
       ('VLU_pagaht', 'Đại học Văn Lang', 'VLU', 'university', false),
       ('VNAM_wgni78', 'Học viện Âm nhạc Quốc gia Việt Nam', 'VNAM', 'academy', false),
       ('VNU_rggsci', 'Đại học Quốc gia Hà Nội', 'VNU', 'university', false),
       ('VNUA_kijjdf', 'Học viện Nông nghiệp Việt Nam', 'VNUA', 'academy', false),
       ('VNU-HCM_asrdrn', 'Đại học Quốc gia TP. Hồ Chí Minh', 'VNU-HCM', 'university', false),
       ('VWA_yljdzb', 'Học viện Phụ nữ Việt Nam', 'VWA', 'academy', false),
       ('WRU_d0dt4c', 'Đại học Thủy lợi', 'WRU', 'university', false),
       ('YDH_wm9ywu', 'Đại học Y Dược - ĐH Huế', 'YDH', 'university', false);